### ISSUE TITLE
"Smarter" use of file copies, conversion to save time 

### ISSUE THREAD

**Issue by quol** [glennmatthews/cot#39]
Per discussion with @glennmatthews opening this to track changes around the following

1. Today with an existing OVF (not OVA) COT will copy the disk files to a temp directory even if it is for an edit-product operation, and the input/output directories are the same.  There are cases when this is undesirable because the potential is there for the edit-product operation to be lengthy.  It may also sometimes be undesirable to copy vmdk's to a tmp dir when converting OVF to OVA.

2. It appears that COT will convert an existing stream optimized vmdk to raw, then back again.  @glennmatthews replied that this was not the case and/or not intended.  Need to just ensure this is happening, and correct if it is not.

**Comment by quol** [comment]
I will get @glennmatthews the data point he needs for #2

**Comment by glennmatthews** [comment]
@quol Can you give my feature/reduce_file_copies branch a try and see how well it works for you?

**Comment by quol** [comment]
It works. Thumbs up.
