### ISSUE TITLE
Setting properties in the OVF

### ISSUE THREAD

**Issue by fdanna** [glennmatthews/cot#50]
I'm trying to generate a VMware Virtual Appliances as part of a build system. When the Appliance is in the user's hands and being deployed (in a vSphere Environment) I want the user to be able to set networking and root password. I see that you can set properties and I've tried this, but they are not exposed when the Appliance is deployed. Comparing what COT generates and what VMware generates from VMware Studio, I noticed the code generated is not the same:

VMware Studio

 <Property ovf:key="ip0" ovf:userConfigurable="true" ovf:type="string">
        <Label>Network 1 IP Address</Label>
        <Description>The IP address for this interface. Leave blank if DHCP is desired.</Description>
      </Property>
      <Property ovf:key="netmask0" ovf:userConfigurable="true" ovf:type="string">
        <Label>Network 1 Netmask</Label>
        <Description>The netmask or prefix for this interface. Leave blank if DHCP is desired.</Description>
      </Property>

COT

 <ovf:Property ovf:key="oe.IP" ovf:type="string" ovf:value="0.0.0.0" />

Is there a way in COT to generate lines with the userConfigurable attribute and no value (assuming that's the problem)?

**Comment by glennmatthews** [comment]
Thanks for the report! I'll start to look into this, but would you be able to provide:

1) The COT command you are using to try and set the properties
2) The PropertySection from the COT-generated OVF.
3) The PropertySection from the VMware Studio-generated OVF.

Thanks!

**Comment by fdanna** [comment]
DOH! I didn't realize the code I pasted was converted. Guess I'm showing my newbie skin.

COT
` <ovf:Property ovf:key="oe.IP" ovf:type="string" ovf:value="0.0.0.0" />
`

Studio
` <Property ovf:key="DNS" ovf:userConfigurable="true" ovf:type="string">
        <Label>DNS</Label>
        <Description>The domain name servers for this VM (comma separated). Leave blank if DHCP is desired.</Description>
      </Property>
      <Property ovf:key="ip0" ovf:userConfigurable="true" ovf:type="string">
        <Label>Network 1 IP Address</Label>
        <Description>The IP address for this interface. Leave blank if DHCP is desired.</Description>
      </Property>
      <Property ovf:key="netmask0" ovf:userConfigurable="true" ovf:type="string">
        <Label>Network 1 Netmask</Label>
        <Description>The netmask or prefix for this interface. Leave blank if DHCP is desired.</Description>
      </Property>
    </ProductSection>`

The command is: cot edit-properties StorageAgent.ovf -p oe.IP=1.2.3.4

I tried calling it different things, but nothing shows up at deploy time. Can't leave the value blank either. I can't seem to find any answers and I appreciate your help!!!

**Comment by glennmatthews** [comment]
Thanks! Looks like I forgot to have COT add the `ovf:userConfigurable` attribute when creating a new property. I'll fix this.

**Comment by fdanna** [comment]
You've made my week! Is there a way for me to create the key pair such that the value will be blank? The value will be filled in by the end user at deploy time. Or from the VMware code, there is no value attribute at all.

**Comment by glennmatthews** [comment]
In the current implementation you can set the value to blank by not specifying anything after the '=' - for example `cot edit-properties StorageAgent.ovf -p oe.IP=`. I think I'll be able to rework it in my fix for this such that the '=' becomes optional as well so this would become `cot edit-properties StorageAgent.ovf -p oe.IP`.

**Comment by glennmatthews** [comment]
I have released COT 1.7.0, which includes a fix for this issue. Thanks for the report and please let me know if you encounter any further issues!

**Comment by glennmatthews** [comment]
Whoops, I almost forgot - I'd be happy to add you to [the Thanks document](http://cot.readthedocs.io/en/latest/thanks.html) if you'd like to provide a name (or just your GitHub user id, if you prefer). Let me know and if so I'll make sure it's included in the next release.

**Comment by fdanna** [comment]
Can't wait to try it out! It's ok, I don't need any recognition :-)
